### ISSUE TITLE
can't find old blog post

### ISSUE THREAD

**Issue by coke** [RapidApp/tpf-blog-live#13]
Trying to post an update about

http://news.perlfoundation.org/2017/06/grant-proposal-revitalize-blog-1.html

but that shows as a 404 (as does https)

This is the URL that I have marked for the original blog post for this grant proposal, and it's linked to in other pages that were successfully converted, e.g.:

https://news.perlfoundation.org/post/may_2017_grant_votes_part_2

Any idea what happened? I'm concerned that other pages were not successfully converted as well.

**Comment by vanstyn** [comment]
@coke - sorry for the delay on this. This had be confused for quite a bit. I finally managed to track the problem down to an issue with your post (in the original export), as well as 7 others, which had the odd case that they did not contain a body, yet they did contain an "extended body". I've now updated the script to handle this case and was able to re-run it (after some finagling) for it to just import those 8 missing posts (As well as associated comments). 

So, your post is finally now back online again, as well as the others. Let me know if you run into further issues.
