### ISSUE TITLE
Control Panel permissions too open

### ISSUE THREAD

**Issue by petek** [RapidApp/tpf-blog-live#3]
Brand new users with no special permissions are able to get to these two pages, which allow extraction of the full user list and the access logs:

http://news.perlfoundation.org/adm/#!/adm/main/db/db_user
http://news.perlfoundation.org/adm/#!/adm/main/db/db_hit (although the IP addr is obfuscated by the load balancer, wherever that is)

We should likely lock those permissions down ASAP.

**Comment by vanstyn** [comment]
The columns are now hidden but i'm still working on the rest of the fix

**Comment by vanstyn** [comment]
This has been fully resolved and is now live
