### ISSUE TITLE
Crash On Username Change

### ISSUE THREAD

**Issue by wbraswell** [RapidApp/tpf-blog-live#7]
Very basic testing of the last bug shows some things are still a bit broken.
https://github.com/RapidApp/tpf-blog-live/issues/6

I logged in with my now-current username "wbraswell" and immediately tried to change back to my old undesirable username "williamn_braswell_jr", which crashed!
![perlfoundation_20191005-rapiblog_username_error](https://user-images.githubusercontent.com/1772630/66258739-65b09180-e76e-11e9-84a6-57c0965070ee.png)

I don't think it actually DID anything, or at least it doesn't seem like it did, because it kept my current "wbraswell" username and I was able to continue using the site.  (Not like last time where everything crashed.)

I then tried to change my username to "willthechill" which did work!  I was able to continue using the website, log out, log back in, all w/out any problems.  I then changed my username back to "wbraswell" and all seems well.  So presumably the only problem is when I tried to change my username to the old "williamn_braswell_jr" value?

**Comment by vanstyn** [comment]
I beleive we established that this is indeed fixed now, so I'm closing. But if I am mistaken, please re-open
